export const surpriseMePrompts = [
    'an armchair in the shape of an avocado',
    'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
    'teddy bears shopping for groceries in Japan, ukiyo-e',
    'an oil painting by Matisse of a humanoid robot playing chess',
    'panda mad scientist mixing sparkling chemicals, digital art',
    "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'an astronaut lounging in a tropical resort in space, vaporwave',
    'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'a stained glass window depicting a hamburger and french fries',
    'a pencil and watercolor drawing of a bright city in the future with flying cars',
    'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
    'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster, knitted out of wool',
    'A plush toy robot sitting against a yellow wall',
    'A synthwave style sunset above the reflecting water of the sea, digital art',
    'Two futuristic towers with a skybridge covered in lush foliage, digital art',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
    'A comic book cover of a superhero wearing headphones',
    'A centered explosion of colorful powder on a black background',
    'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
    'A photo of a white fur monster standing in a purple room',
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    'A Samurai riding a Horse on Mars, lomography.',
    'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
    'A realistic photograph of a young woman with blue eyes and blonde hair',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'A BBQ that is alive, in the style of a Pixar animated movie',
    'A futuristic cyborg dance club, neon lights',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A hamburger in the shape of a Rubik’s cube, professional food photography',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A Dinosaur exploring Cape Town, photography',
    'A Man falling in Love with his Computer, digital art',
    'A photograph of a cyborg exploring Tokyo at night, lomography',
    'Dracula walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave aeroplane',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A Space Shuttle flying above Cape Town, digital art',
    'A serene beach sunset in Bali, with palm trees and gentle waves, watercolor style',
    'An ancient castle perched atop a misty cliff, overlooking a vast forest, fantasy painting',
    'A futuristic cityscape with towering skyscrapers, flying cars, and holographic billboards, cyberpunk illustration',
    'A cozy cabin nestled in a snowy mountain landscape, surrounded by pine trees, oil painting',
    'A group of majestic dragons soaring through the clouds in a mythical sky, digital fantasy art',
    'A lone astronaut exploring a mysterious alien planet, with strange flora and fauna, sci-fi concept art',
    'A charming café scene in Paris, with cobblestone streets, colorful umbrellas, and Parisian architecture, impressionist painting',
    'A fantastical underwater world with vibrant coral reefs, exotic fish, and mermaids, watercolor and ink',
    'A magical forest illuminated by fireflies, fairies, and glowing mushrooms, whimsical digital art',
    'A steam-powered locomotive traveling through a vast desert landscape, steampunk-inspired illustration',
    'A breathtaking view of the Northern Lights dancing over a frozen Arctic landscape, digital painting',
    'A bustling marketplace in Marrakech, filled with merchants, spices, and traditional Moroccan architecture, mixed-media collage',
    'An enchanted castle floating among the clouds, home to wizards and magical creatures, fantasy concept art',
    'A retro-futuristic city on Mars, with domed structures, rocket launches, and robotic inhabitants, vintage poster design',
    'A serene waterfall hidden deep in a lush rainforest, with vibrant flora and wildlife, oil on canvas',
    'A whimsical hot air balloon festival in a pastel-colored sky, with floating clouds, digital art',
    'A mythical sea creature emerging from the depths of the ocean, surrounded by bioluminescent creatures, fantasy concept art',
    'A vintage train station bustling with travelers and steam locomotives, retro-style illustration',
    'An otherworldly alien landscape with floating islands and strange rock formations, sci-fi digital painting',
    'A tranquil Japanese garden with cherry blossom trees in full bloom, watercolor and ink',
    'A wild safari adventure with elephants, zebras, and lions roaming the savannah, wildlife illustration',
    'A magical library filled with ancient tomes and mystical artifacts, illuminated manuscript style',
    'A surreal underwater city inhabited by merfolk and aquatic creatures, dreamlike digital art',
    'A vibrant street market in Marrakech, with colorful textiles and spices, travel poster design',
    'An enchanted winter forest with talking animals and hidden fairy doors, storybook illustration',
    'A mesmerizing dance performance of ballerinas in elegant tutus, watercolor and pencil sketch',
    'A haunted castle on a hill with thunderstorm clouds and eerie moonlight, gothic painting',
    'A futuristic space colony on a distant planet, with advanced technology and floating structures, sci-fi concept art',
    'A lush vineyard in Tuscany, Italy, with rolling hills and grapevines, oil on canvas',
    'A steampunk airship soaring through the skies, powered by gears and steam engines, retro-futuristic illustration',
    'A mystical portal leading to an enchanted realm, surrounded by ancient ruins, fantasy painting',
    'A vibrant city street during a rainy night, with reflections and neon lights, digital neon art',
    'An epic battle scene between knights and dragons in a medieval landscape, digital fantasy art',
    'A serene pagoda nestled in a serene mountain valley, surrounded by cherry blossoms, ink wash painting',
    'A secret garden hidden behind an old mansion, with overgrown vegetation and hidden paths, watercolor and pen',
    'A futuristic cityscape with sleek skyscrapers and flying cars, bathed in neon lights, digital art',
    'A majestic underwater kingdom ruled by a mermaid queen, surrounded by marine life, fantasy concept art',
    'An ancient Egyptian pyramid rising from the desert sands, with hieroglyphs and mystical symbols, historical illustration',
    'A tranquil lakeside cabin beneath a starry night sky, surrounded by mountains, watercolor painting',
    'A fantastical forest filled with mythical creatures like unicorns and centaurs, digital fantasy art',
    'A bustling night market in Tokyo, with food stalls, lanterns, and vibrant energy, anime-inspired illustration',
    'An ethereal celestial event with a comet passing through a galaxy, cosmic digital art',
    'A medieval castle perched on a cliff overlooking a picturesque village, oil on canvas',
    'A magical carousel with intricate wooden carvings and flying mythical creatures, dreamlike illustration',
    'A dramatic storm at sea with crashing waves and a lighthouse guiding ships, maritime painting',
    'A hidden elven city nestled within a lush forest, with treetop dwellings, fantasy landscape art',
    'A high-tech cybernetic laboratory filled with holographic displays and advanced robots, sci-fi concept art',
    'A serene Zen garden with raked sand, bonsai trees, and a stone pagoda, Japanese ink painting',
    'An adventurous pirate ship sailing the open seas, with a crew of swashbucklers, digital illustration',
    'A charming European village square with cobblestones, cafes, and musicians, watercolor and ink sketch',
    'A mystical cave filled with glowing crystals and ancient artifacts, magical digital art',
    'A vintage road trip scene with classic cars, retro diners, and Route 66 signs, nostalgic poster design',
    'A grand ballroom dance with elegant ball gowns and dashing tuxedos, rococo-style painting',
    "A whimsical winter wonderland with talking snowmen and friendly woodland creatures, children's book illustration",
    'A futuristic spaceport on an alien planet, with towering spaceships and bustling alien species, sci-fi concept art',
  ];